# -*- coding: utf-8 -*-
"""FakeNewsDectection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184Txf2btJv4wqd4iKz8B1ngX25-RGZX3
"""

!pip install nltk
import pandas as pd
import numpy as np
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords  # remove words like for the with in of
from nltk.stem.porter import PorterStemmer # loving loved==love convert into base word
from sklearn.feature_extraction.text import TfidfVectorizer # Loved=[0.0]
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

news_df=pd.read_csv('train.csv')
news_df.head()

news_df.shape

news_df.isna().sum()   # it tells how many values are NaN in id,title,authro,text,label

news_df=news_df.fillna(' ')  # it fill all the NaN values with ' '
news_df.isna().sum()

news_df['content']=news_df['author']+news_df['title']
news_df

news_df['content'][20796]

# stemming
ps=PorterStemmer()



def stemming(content):
    # Handle the case where content is None or not a string
    if content is None:
        content = ""  # Assign an empty string if content is None
    elif not isinstance(content, str):
        content = str(content)  # Convert to string if it's not a string

    # Replace non-alphabet characters with space
    stemmed_content = re.sub('[^a-zA-Z]', ' ', content)

    # Convert to lowercase
    stemmed_content = stemmed_content.lower()

    # Split the string into words
    stemmed_content = stemmed_content.split()

    # Remove stopwords and apply stemming
    stemmed_content = [ps.stem(word) for word in stemmed_content if word not in stopwords.words('english')]

    # Join the stemmed words back into a single string
    stemmed_content = ' '.join(stemmed_content)

    return stemmed_content

news_df['content'] = news_df['content'].apply(stemming)

news_df['content']

X=news_df['content'].values
Y=news_df['label'].values
print(X)

vector=TfidfVectorizer()
vector.fit(X)
X=vector.transform(X)
print(X)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)
X_train.shape

model=LogisticRegression()
model.fit(X_train,Y_train)

train_y_pred=model.predict(X_train)
train_accuracy=accuracy_score(train_y_pred,Y_train)
print(train_accuracy)

test_y_pred=model.predict(X_test)
test_accuracy=accuracy_score(test_y_pred,Y_test)
print(test_accuracy)

# prediction
x_new=X_test[2]
prediction=model.predict(x_new)
if prediction[0]==0:
  print('The news is real')
else:
  print('The news is fake')